{% set version = "3.1-6" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-spatstat.data
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/spatstat.data_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/spatstat.data/spatstat.data_{{ version }}.tar.gz
  sha256: ffb0e37c27bdcced84416bf6dc5dfcf8a26bd555200cff1194bf6d0f407294de

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-matrix
    - r-spatstat.utils >=3.1_2
  run:
    - r-base
    - r-matrix
    - r-spatstat.utils >=3.1_2

test:
  commands:
    - $R -e "library('spatstat.data')"           # [not win]
    - "\"%R%\" -e \"library('spatstat.data')\""  # [win]

about:
  home: http://www.spatstat.org
  dev_url: https://github.com/spatstat/spatstat.data
  license: GPL-2.0-or-later
  summary: Contains all the datasets for the 'spatstat' family of packages.
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
